DZ = [\
["abdomenLower","spine1"],
["abdomenUpper","spine2"],
["chestLower","spine3"],
["chestUpper","spine1"],
["neckLower","neck1"],
["neckUpper","neck2"],
["head","head"],
["lowerJaw","jaw"],
["lPectoral","breast_l"],
["lShldrBend","upperarm_l"],
["rPrectoral","breast_r"],
["lCollar","shoulder_l"],
["lShldrBend","upperarm_l"],
["lShldrTwist","upperarm_twist1_l"],
["lForearmBend","forearm_l"],
["lForearmTwist","forearm_twist1_l"],
["lHand","hand_l"],
["lCarpal1","palm1_l"],
["lCarpal2","palm2_l"],
["lCarpal3","palm3_l"],
["lCarpal4","palm4_l"],
["lThumb1","finger_thumb1_l"],
["lThumb2","finger_thumb2_l"],
["lThumb3","finger_thumb3_l"],
["lIndex1","finger_index1_l"],
["lIndex2","finger_index2_l"],
["lIndex3","finger_index3_l"],
["lMid1","finger_middle1_l"],
["lMid2","finger_middle2_l"],
["lMid3","finger_middle3_l"],
["lRing1","finger_ring1_l"],
["lRing2","finger_ring2_l"],
["lRing3","finger_ring3_l"],
["lPinky1","finger_pinky1_l"],
["lPinky2","finger_pinky2_l"],
["lPinky3","finger_pinky3_l"],            
["lThighBend","thigh_l"],
["lThighTwist","thigh_twist1_l"],
["lShin","shin_l"],
["lFoot","foot_l"],
["lMetatarsals","metatarsals_l"],
["lToe","toe_l"],
["lSmallToe4","toe_pinky1_l"],
["lSmallToe4_2","toe_pinky2_l"],
["lSmallToe3","toe_ring1_l"],
["lSmallToe3_2","toe_ring2_l"],
["lSmallToe2","toe_middle1_l"],
["lSmallToe2_2","toe_middle2_l"],
["lSmallToe1","toe_index1_l"],
["lSmallToe1_2","toe_index2_l"],
["lBigToe","toe_big1_l"],
["lBigToe_2","toe_big2_l"]
]

HW = 
pelvis,pelvis
hip,hip
spine1,abdomen
spine2,abdomen2
spine3,chest
spine4,chest2
neck1,neck
neck2,neck2
neck3,neck3
neck4,neck4
neck5,neck5
neck6,neck6
head,head
ear_l,lEar
ear_r,rEar
eye_l,lEye
eye_r,rEye
shoulder_l,lShldr
shoulder_r,rShldr
upperarm_l,lUpperarm
upperarm_r,rUpperarm
forearm_l,lForeArm
forearm_r,rForeArm
forecannon_l,lForeCannon
forecannon_r,rForeCannon
forepastern_l,lForePastern
forepastern_r,rForePastern
forehoof_l,lForeHoof
forehoof_r,rForeHoof
thigh_l,lThigh
thigh_r,rThigh
gaskin_l,lGaskin
gaskin_r,rGaskin
hindcannon_l,lHindCannon
hindcannon_r,rHindCannon
hindpastern_l,lHindPastern
hindpastern_r,rHindPastern
hindhoof_l,lHindHoof
hindhoof_r,rHindHoof
tail1,tail1
tail2,tail2
tail3,tail3
tail4,tail4
tail5,tail5
tail6,tail6
tail7,tail7
tail8,tail8
tail9,tail9